### PR TITLE
Add Kubernetes cronjob

### PR DESCRIPTION
**Pull request by davidgasquez**
Heya @jwinternheimer! This PR adds the cronjob file to this repo. Is still not enabled in the Kubernetes cluster and wanted to check with you about the frequency. 

Right now is set to be executed each day at 14:00, does that sounds a good schedule?

### CODE REVIEW

**Comment by jwinternheimer** [comment]
That sounds amazing! Thanks so much for jumping on this @davidgasquez! 

bitmoji

**Review by jwinternheimer — APPROVED** [review]
Looks great to me, thanks again @davidgasquez!

**Comment by davidgasquez** [comment]
One quick request I forgot to mention, would you mind building the image again and pushing it to Docker Hub? 😅 I made a small tweak to the name and the image is not in Docker Hub to be pulled in Kubernetes. Sorry!

**Comment by jwinternheimer** [comment]
No problem! It's done! https://hub.docker.com/r/julheimer/customer_health_scores/

**Pull request merged**
